import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Knowledge } from "@/types";
import Link from "next/link";
import Header from "@/components/Header";
import ResponsiveAppBar from "@/components/ResponsiveAppBar";
import { GetServerSideProps } from "next";
import { withAuthServerSideProps } from "../lib/auth";

export const getServerSideProps: GetServerSideProps =
  withAuthServerSideProps("/knowledges");

//////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////
export default function Home(props:any) {
  return (
    <>
      <Head>
        <title>EX-Knowledge</title>
        <meta title="description" content="Generated by create next app" />
        <meta title="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div>
          <ResponsiveAppBar title="" />
          <div>こんにちは！！{props.user.email}さん！！！！！！！！</div>
        </div>
        <div className={styles.homeContainer}>
          {props.knowledges.map((knowledge: Knowledge) => (
            <div key={knowledge.id} className={styles.postCard}>
              <p>{knowledge.title}</p>
              <p>{knowledge.content}</p>
              <button className={styles.likeButton}>Like</button>
              <button className={styles.superLikeButton}>super Like!</button>
              <button className={styles.knowButton}>Know</button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
